apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-apr8-chatbot-vllm-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-apr8-chatbot-vllm-gitops
    spec:
      serviceAccountName: apr8-chatbot-vllm-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=apr8-chatbot-vllm-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/apr8-chatbot-vllm-notebook -- git clone https://github.com/jdubrick-ai/apr8-chatbot-vllm
      restartPolicy: Never
